services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build:
      context: ./betblitz-recsys-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      ARTIFACT_DIR: /app/artifacts
      REDIS_ENABLED: "true"
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./betblitz-recsys-api/artifacts:/app/artifacts:ro
    depends_on:
      redis:
        condition: service_healthy

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.10.2
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
      - ./mlartifacts:/mlflow/mlartifacts
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --serve-artifacts
      --artifacts-destination /mlflow/mlartifacts
      --backend-store-uri sqlite:////mlflow/mlruns/mlflow.db

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus
